
runtime: nodejs
env: flex

service: pixels-proxy-ping

network:
  session_affinity: true
  name: default
  subnetwork_name: default

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 60

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

manual_scaling:
  instances: 1